import type { Schema } from "@repo/types";

export const stubSchema = [
  {
    name: "User",
    schema: null,
    access: "QUERYABLE",
    context: null,
    columns: [
      {
        name: "id",
        dbName: "id",
        rename: null,
        notes: null,
        type: "string",
        effectiveType: "string",
        conversion: null,
        unit: null,
        relation: [],
      },
      {
        name: "name",
        dbName: "name",
        rename: null,
        notes: null,
        type: "string",
        effectiveType: "string",
        conversion: null,
        unit: null,
        relation: [],
      },
      {
        name: "age",
        dbName: "age",
        rename: null,
        notes: null,
        type: "number",
        effectiveType: "number",
        conversion: null,
        unit: null,
        relation: [],
      },
      {
        name: "active",
        dbName: "active",
        rename: null,
        notes: null,
        type: "boolean",
        effectiveType: "boolean",
        conversion: null,
        unit: null,
        relation: [],
      },
      {
        name: "createdAt",
        dbName: "createdAt",
        rename: null,
        notes: null,
        type: "DateTime",
        effectiveType: "DateTime",
        conversion: null,
        unit: null,
        relation: [],
      },
    ],
    computedColumns: [
      {
        name: "computedScore",
        table: { name: "User" },
        type: "number",
        ast: null,
        unit: null,
        notes: null,
      },
    ],
    outwardRelations: [
      {
        name: "profile",
        relationId: "User_profile",
        targetTable: { name: "Profile" },
        targetSchema: null,
        isList: false,
        selected: true,
        source: "FK",
        status: "VALID",
        errorTag: null,
        sourceColumns: ["id"],
        targetColumns: ["userId"],
      },
      {
        name: "posts",
        relationId: "User_posts",
        targetTable: { name: "Post" },
        targetSchema: null,
        isList: true,
        selected: true,
        source: "FK",
        status: "VALID",
        errorTag: null,
        sourceColumns: ["id"],
        targetColumns: ["authorId"],
      },
    ],
    condition: null,
    accessPolicy: null,
  },
  {
    name: "Profile",
    schema: null,
    access: "QUERYABLE",
    context: null,
    columns: [
      {
        name: "id",
        dbName: "id",
        rename: null,
        notes: null,
        type: "string",
        effectiveType: "string",
        conversion: null,
        unit: null,
        relation: [],
      },
      {
        name: "userId",
        dbName: "userId",
        rename: null,
        notes: null,
        type: "string",
        effectiveType: "string",
        conversion: null,
        unit: null,
        relation: [],
      },
      {
        name: "bio",
        dbName: "bio",
        rename: null,
        notes: null,
        type: "string",
        effectiveType: "string",
        conversion: null,
        unit: null,
        relation: [],
      },
      {
        name: "reputation",
        dbName: "reputation",
        rename: null,
        notes: null,
        type: "number",
        effectiveType: "number",
        conversion: null,
        unit: null,
        relation: [],
      },
    ],
    computedColumns: [],
    outwardRelations: [],
    condition: null,
    accessPolicy: null,
  },
  {
    name: "Post",
    schema: null,
    access: "QUERYABLE",
    context: null,
    columns: [
      {
        name: "authorId",
        dbName: "authorId",
        rename: null,
        notes: null,
        type: "string",
        effectiveType: "string",
        conversion: null,
        unit: null,
        relation: [],
      },
      {
        name: "views",
        dbName: "views",
        rename: null,
        notes: null,
        type: "number",
        effectiveType: "number",
        conversion: null,
        unit: null,
        relation: [],
      },
      {
        name: "published",
        dbName: "published",
        rename: null,
        notes: null,
        type: "boolean",
        effectiveType: "boolean",
        conversion: null,
        unit: null,
        relation: [],
      },
      {
        name: "publishedAt",
        dbName: "publishedAt",
        rename: null,
        notes: null,
        type: "DateTime",
        effectiveType: "DateTime",
        conversion: null,
        unit: null,
        relation: [],
      },
      {
        name: "title",
        dbName: "title",
        rename: null,
        notes: null,
        type: "string",
        effectiveType: "string",
        conversion: null,
        unit: null,
        relation: [],
      },
    ],
    computedColumns: [],
    outwardRelations: [],
    condition: null,
    accessPolicy: null,
  },
] satisfies Schema;
