packages:
  - apps/*
  - packages/*
  - infra

minimumReleaseAge: 180

onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - better-sqlite3
  - core-js
  - esbuild
  - prisma
  - protobufjs
  - sharp
  - unrs-resolver
  - workerd

patchedDependencies:
  "@cloudflare/workers-oauth-provider@0.2.2": patches/@cloudflare__workers-oauth-provider@0.2.2.patch
  langsmith@0.4.4: patches/langsmith@0.4.4.patch
