packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - better-sqlite3
  - core-js
  - esbuild
  - prisma
  - protobufjs
  - sharp
  - unrs-resolver
  - workerd
