packages:
  - .

minimumReleaseAge: 180

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - core-js
  - esbuild
  - prisma
  - protobufjs
  - sharp
  - unrs-resolver

patchedDependencies:
  '@langchain/openai@1.2.0': patches/@langchain__openai@1.2.0.patch
  langsmith@0.4.0: patches/langsmith@0.4.0.patch
