/* ============================================================
   Demo Database Schema for Inconvo
   ============================================================ */

BEGIN;

CREATE TABLE public.organisations (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        varchar(255) NOT NULL UNIQUE,
    created_at  timestamptz  NOT NULL DEFAULT now()
);

/* ============================================================
   Shared-table, multi-tenant business schema
   ============================================================ */

-- 1. Users -----------------------------------------------
CREATE TABLE public.users (
    organisation_id integer NOT NULL,
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address         varchar(255),
    email           varchar(255),
    password        varchar(255),
    name            varchar(255),
    city            varchar(255),
    longitude       double precision,
    birth_date      date,
    zip             char(5),
    latitude        double precision,
    created_at      timestamp without time zone,
    last_order_at   timestamp without time zone,
    FOREIGN KEY (organisation_id) REFERENCES public.organisations(id)
);

-- 2. Products -------------------------------------------------
CREATE TABLE public.products (
    organisation_id integer NOT NULL,
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ean             char(13),
    title           varchar(255),
    category        varchar(255),
    price           double precision,
    stock_level     integer,
    created_at      timestamp without time zone,
    FOREIGN KEY (organisation_id) REFERENCES public.organisations(id)
);

-- 3. Orders ---------------------------------------------------
CREATE TABLE public.orders (
    organisation_id integer NOT NULL,
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         integer,
    product_id      integer,
    subtotal        double precision,
    tax             double precision,
    discount        double precision,
    created_at      timestamp without time zone,
    quantity        integer,
    FOREIGN KEY (organisation_id) REFERENCES public.organisations(id),
    FOREIGN KEY (user_id) REFERENCES public.users(id),
    FOREIGN KEY (product_id) REFERENCES public.products(id)
);

-- 4. Reviews --------------------------------------------------
CREATE TABLE public.reviews (
    organisation_id integer NOT NULL,
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id      integer,
    user_id         integer,
    rating          smallint,
    comment         text,
    created_at      timestamp without time zone,
    FOREIGN KEY (organisation_id) REFERENCES public.organisations(id),
    FOREIGN KEY (user_id) REFERENCES public.users(id),
    FOREIGN KEY (product_id) REFERENCES public.products(id)
);

/* ============================================================
   Convenience indexes
   ============================================================ */

CREATE INDEX idx_users_org  ON public.users (organisation_id);
CREATE INDEX idx_products_org   ON public.products  (organisation_id);
CREATE INDEX idx_orders_org     ON public.orders    (organisation_id);
CREATE INDEX idx_reviews_org    ON public.reviews   (organisation_id);

COMMIT;

BEGIN;

INSERT INTO public.organisations (id, name, created_at)
VALUES
    (1, 'Apple', NOW()),
    (2, 'Tesla', NOW()),
    (3, 'Logitech', NOW());


-- Insert Products
-- Apple (organisation_id = 1) - 15 items
INSERT INTO public.products
(organisation_id, ean, title, category, price, stock_level, created_at)
VALUES
    (1,'1234567890123','iPhone 15','Smartphone',999.99,15,NOW()),
    (1,'1234567890124','MacBook Pro','Laptop',2499.99,500,NOW()),
    (1,'1234567890125','AirPods Pro','Audio',249.99,12,NOW()),
    (1,'1234567890126','iPad Pro','Tablet',1099.99,100,NOW()),
    (1,'1234567890127','Apple Watch','Wearables',399.99,43,NOW()),
    (1,'1234567890130','Apple TV 4K','Streaming',149.99,400,NOW()),
    (1,'1234567890131','HomePod (2nd gen)','Smart Speaker',299.99,350,NOW()),
    (1,'1234567890132','Mac mini (M2)','Desktop',699.99,18,NOW()),
    (1,'1234567890133','Mac Studio (M3 Max)','Desktop',3999.99,16,NOW()),
    (1,'1234567890134','Magic Keyboard w/ Touch ID','Peripherals',149.99,600,NOW()),
    (1,'1234567890135','Magic Mouse','Peripherals',79.99,800,NOW()),
    (1,'1234567890136','iMac 24" (M3)','Desktop',1499.99,180,NOW()),
    (1,'1234567890137','AirTag (4-pack)','Accessories',99.00,9,NOW()),
    (1,'1234567890138','Apple Vision Pro','Spatial Computer',3499.00,40,NOW()),
    (1,'1234567890139','Apple Pencil (USB-C)','Accessories',79.99,900,NOW());

-- Tesla (organisation_id = 2) - 15 items
INSERT INTO public.products
(organisation_id, ean, title, category, price, stock_level, created_at)
VALUES
    (2,'2345678901234','Model S','Electric Vehicle',79999.99,150,NOW()),
    (2,'2345678901235','Model 3','Electric Vehicle',45999.99,100,NOW()),
    (2,'2345678901236','Powerwall','Energy',8500.00,200,NOW()),
    (2,'2345678901237','Model X','Electric Vehicle',89999.99,100,NOW()),
    (2,'2345678901238','Solar Roof','Energy',25000.00,80,NOW()),
    (2,'2345678901240','Model Y','Electric Vehicle',52999.99,250,NOW()),
    (2,'2345678901241','Cybertruck Dual Motor','Electric Vehicle',79999.99,120,NOW()),
    (2,'2345678901242','Roadster (Next Gen)','Electric Vehicle',200000.00,15,NOW()),
    (2,'2345678901243','Tesla Semi (Class 8)','Electric Vehicle',180000.00,8,NOW()),
    (2,'2345678901244','Megapack 2XL','Energy',1900000.00,5,NOW()),
    (2,'2345678901245','Solar Panel 400 W','Energy',350.00,1000,NOW()),
    (2,'2345678901246','Powerpack','Energy',172000.00,20,NOW()),
    (2,'2345678901247','Supercharger V4 Stall','Charging Infra',30000.00,60,NOW()),
    (2,'2345678901248','Wall Connector Gen 3','Charging Equip',475.00,700,NOW()),
    (2,'2345678901249','Solar Inverter 10 kW','Energy',4100.00,90,NOW());

-- Logitech (organisation_id = 3) - 15 items
INSERT INTO public.products
(organisation_id, ean, title, category, price, stock_level, created_at)
VALUES
    (3,'3456789012345','MX Master 3S Mouse','Peripherals',99.99,500,NOW()),
    (3,'3456789012346','G Pro X Keyboard','Gaming',129.99,400,NOW()),
    (3,'3456789012347','Brio 4K Webcam','Video Conf.',199.99,12,NOW()),
    (3,'3456789012348','Zone Vibe 100 Headset','Audio',119.99,350,NOW()),
    (3,'3456789012349','Logitech StreamCam','Content Creation',169.99,3,NOW()),
    (3,'3456789012355','MX Keys S Keyboard','Peripherals',109.99,550,NOW()),
    (3,'3456789012356','G Pro Wireless Mouse','Gaming',129.99,600,NOW()),
    (3,'3456789012357','Blue Yeti X Mic','Audio',169.99,450,NOW()),
    (3,'3456789012358','G923 Racing Wheel','Gaming',399.99,320,NOW()),
    (3,'3456789012359','C920s Pro Webcam','Video Conf.',69.99,700,NOW()),
    (3,'3456789012360','Lift Vertical Mouse','Peripherals',79.99,10,NOW()),
    (3,'3456789012361','Ergo K860 Split KB','Peripherals',129.99,350,NOW()),
    (3,'3456789012362','Rally Bar','Video Conf.',3999.99,40,NOW()),
    (3,'3456789012363','Logi Dock','Collaboration',399.99,150,NOW()),
    (3,'3456789012364','K380 Multi-Device KB','Peripherals',39.99,9,NOW());

COMMIT;
