import * as fs from "fs/promises";
import * as path from "path";
import YAML from "yaml";
import { logInfo } from "../process/output.js";
import type {
  AgentInfo,
  ConnectionInfo,
  ConnectionSemanticModelResponse,
  ConnectionSemanticModelTable,
  OrgInfo,
  ShareableConnectionInfo,
  UserContextResponse,
} from "./types.js";
import { PlatformApiClient } from "./api-client.js";

const AGENT_PULL_CONCURRENCY = 4;
const CONNECTION_PULL_CONCURRENCY = 6;
const SLUG_MAP_FILE = ".slug-map.yaml";
const SAFE_PERSISTED_SLUG_PATTERN = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

async function mapWithConcurrency<T, R>(
  items: T[],
  concurrency: number,
  mapper: (item: T, index: number) => Promise<R>,
): Promise<R[]> {
  if (items.length === 0) {
    return [];
  }

  const limit = Math.max(1, Math.min(concurrency, items.length));
  const results: R[] = new Array(items.length);
  let cursor = 0;

  const runWorker = async () => {
    while (true) {
      const index = cursor;
      cursor += 1;
      if (index >= items.length) {
        return;
      }
      results[index] = await mapper(items[index]!, index);
    }
  };

  await Promise.all(Array.from({ length: limit }, () => runWorker()));
  return results;
}

async function pathExists(targetPath: string): Promise<boolean> {
  try {
    await fs.access(targetPath);
    return true;
  } catch {
    return false;
  }
}

const GENERATED_FILE_HEADER =
  "# !!! This file is generated by the Inconvo CLI. Do not edit directly. !!!\n";

async function writeYamlFile(targetPath: string, value: unknown): Promise<void> {
  await fs.mkdir(path.dirname(targetPath), { recursive: true });
  await fs.writeFile(targetPath, GENERATED_FILE_HEADER + YAML.stringify(value));
}

export function slugify(name: string): string {
  const slug = name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
  return slug || "unnamed";
}

function modelRoot(repoRoot: string): string {
  return path.join(repoRoot, ".inconvo");
}

function sortByNameThenId<T extends { id: string; name: string }>(items: T[]): T[] {
  return [...items].sort(
    (left, right) =>
      left.name.localeCompare(right.name) || left.id.localeCompare(right.id),
  );
}

function nextAvailableSlug(baseSlug: string, used: Set<string>): string {
  if (!used.has(baseSlug)) {
    return baseSlug;
  }

  let suffix = 2;
  while (true) {
    const candidate = `${baseSlug}-${suffix}`;
    if (!used.has(candidate)) {
      return candidate;
    }
    suffix += 1;
  }
}

function isSafePersistedSlug(slug: string): boolean {
  return SAFE_PERSISTED_SLUG_PATTERN.test(slug);
}

function parseSlugMap(raw: unknown): Record<string, string> {
  if (!raw || typeof raw !== "object" || Array.isArray(raw)) {
    return {};
  }

  const parsed = raw as Record<string, unknown>;
  const result: Record<string, string> = {};
  for (const [id, slug] of Object.entries(parsed)) {
    if (typeof id !== "string" || typeof slug !== "string") {
      continue;
    }
    const trimmedId = id.trim();
    const trimmedSlug = slug.trim();
    if (trimmedId.length === 0 || trimmedSlug.length === 0) {
      continue;
    }
    if (!isSafePersistedSlug(trimmedSlug)) {
      continue;
    }
    result[trimmedId] = trimmedSlug;
  }
  return result;
}

async function readSlugMap(directory: string): Promise<Record<string, string>> {
  const slugMapPath = path.join(directory, SLUG_MAP_FILE);
  if (!(await pathExists(slugMapPath))) {
    return {};
  }

  const raw = await fs.readFile(slugMapPath, "utf8");
  return parseSlugMap(YAML.parse(raw));
}

function toSortedRecord(record: Record<string, string>): Record<string, string> {
  return Object.fromEntries(
    Object.entries(record).sort(([left], [right]) => left.localeCompare(right)),
  );
}

function resolveScopedSlugs<T extends { id: string; name: string }>(params: {
  entities: T[];
  existingMap: Record<string, string>;
  preserveUnknown: boolean;
}): Map<string, string> {
  const sortedEntities = sortByNameThenId(params.entities);
  const entityIds = new Set(sortedEntities.map((entity) => entity.id));
  const used = new Set<string>();
  const result = new Map<string, string>();

  if (params.preserveUnknown) {
    for (const [id, slug] of Object.entries(params.existingMap)) {
      if (!entityIds.has(id)) {
        used.add(slug);
      }
    }
  }

  for (const entity of sortedEntities) {
    const existingSlug = params.existingMap[entity.id];
    if (existingSlug && !used.has(existingSlug)) {
      result.set(entity.id, existingSlug);
      used.add(existingSlug);
    }
  }

  for (const entity of sortedEntities) {
    if (result.has(entity.id)) {
      continue;
    }
    const baseSlug = slugify(entity.name);
    const slug = nextAvailableSlug(baseSlug, used);
    result.set(entity.id, slug);
    used.add(slug);
  }

  return result;
}

function buildSlugMapRecord(params: {
  slugs: Map<string, string>;
  existingMap: Record<string, string>;
  preserveUnknown: boolean;
}): Record<string, string> {
  const next: Record<string, string> = {};

  if (params.preserveUnknown) {
    for (const [id, slug] of Object.entries(params.existingMap)) {
      if (!params.slugs.has(id)) {
        next[id] = slug;
      }
    }
  }

  for (const [id, slug] of params.slugs) {
    next[id] = slug;
  }

  return toSortedRecord(next);
}

function tableNameFromPayload(table: ConnectionSemanticModelTable): string {
  if (typeof table.name !== "string" || table.name.trim() === "") {
    throw new Error("Encountered table without a valid name.");
  }
  return table.name;
}

async function removeStaleChildren(
  directory: string,
  keepNames: Set<string>,
): Promise<void> {
  if (!(await pathExists(directory))) {
    return;
  }

  const entries = await fs.readdir(directory, { withFileTypes: true });
  await Promise.all(
    entries
      .filter((entry) => !keepNames.has(entry.name))
      .map((entry) =>
        fs.rm(path.join(directory, entry.name), {
          recursive: true,
          force: true,
        }),
      ),
  );
}

interface AgentPullData {
  agent: AgentInfo;
  userContextResponse: UserContextResponse;
  selectedConnections: ConnectionInfo[];
  models: Array<{
    connection: ConnectionInfo;
    model: ConnectionSemanticModelResponse;
  }>;
  shareable: ShareableConnectionInfo[];
}

export async function pullAgentsToWorkspace(params: {
  client: PlatformApiClient;
  repoRoot: string;
  org: OrgInfo;
  selectedAgents: AgentInfo[];
  selectedConnectionId?: string;
  pruneUnselectedAgents?: boolean;
}): Promise<{
  pulledAgents: number;
  pulledConnections: number;
}> {
  const rootDir = modelRoot(params.repoRoot);
  const agentsDir = path.join(rootDir, "agents");
  const connectionsDir = path.join(rootDir, "connections");
  await fs.mkdir(agentsDir, { recursive: true });
  await fs.mkdir(connectionsDir, { recursive: true });
  const preserveUnknownAgents = params.pruneUnselectedAgents === false;
  const preserveUnknownConnectionsGlobal =
    params.pruneUnselectedAgents === false || Boolean(params.selectedConnectionId);
  const existingAgentSlugMap = await readSlugMap(agentsDir);
  const existingConnectionSlugMap = await readSlugMap(connectionsDir);
  const agentSlugs = resolveScopedSlugs({
    entities: params.selectedAgents,
    existingMap: existingAgentSlugMap,
    preserveUnknown: preserveUnknownAgents,
  });

  // Clean up legacy orgs/ structure if present
  const legacyOrgsDir = path.join(modelRoot(params.repoRoot), "orgs");
  if (await pathExists(legacyOrgsDir)) {
    await fs.rm(legacyOrgsDir, { recursive: true, force: true });
    logInfo("Migrated .inconvo/ folder structure. Old orgs/ directory removed.");
  }

  const fetchedAgents = await mapWithConcurrency(
    params.selectedAgents,
    AGENT_PULL_CONCURRENCY,
    async (agent): Promise<AgentPullData> => {
      const [userContextResponse, connections] = await Promise.all([
        params.client.getAgentUserContext(agent.id),
        params.client.listAgentConnections(agent.id),
      ]);

      let selectedConnections = [...connections];
      if (params.selectedConnectionId) {
        const matched = connections.find(
          (connection) => connection.id === params.selectedConnectionId,
        );
        if (!matched) {
          throw new Error(
            `Connection ${params.selectedConnectionId} not found for agent ${agent.id}.`,
          );
        }
        selectedConnections = [matched];
      }

      selectedConnections.sort((left, right) =>
        left.name.localeCompare(right.name),
      );

      const models = await mapWithConcurrency(
        selectedConnections,
        CONNECTION_PULL_CONCURRENCY,
        async (connection) => {
          const model = await params.client.getConnectionSemanticModel(
            agent.id,
            connection.id,
          );
          return {
            connection,
            model,
          };
        },
      );

      const shareable = await params.client.listShareableConnections(agent.id);
      const sortedShareable = [...shareable].sort((left, right) =>
        left.id.localeCompare(right.id),
      );

      return {
        agent,
        userContextResponse,
        selectedConnections,
        models,
        shareable: sortedShareable,
      };
    },
  );

  const pulledConnectionCounts = fetchedAgents.map((entry) => entry.models.length);

  const uniqueConnections = new Map<string, ConnectionInfo>();
  const modelByConnectionId = new Map<string, ConnectionSemanticModelResponse>();
  for (const entry of fetchedAgents) {
    for (const { connection, model } of entry.models) {
      if (!uniqueConnections.has(connection.id)) {
        uniqueConnections.set(connection.id, connection);
      }
      if (!modelByConnectionId.has(connection.id)) {
        modelByConnectionId.set(connection.id, model);
      }
    }
  }

  const connectionSlugs = resolveScopedSlugs({
    entities: sortByNameThenId(Array.from(uniqueConnections.values())),
    existingMap: existingConnectionSlugMap,
    preserveUnknown: preserveUnknownConnectionsGlobal,
  });

  const keepConnectionSnapshotDirs = new Set<string>();
  for (const connection of sortByNameThenId(Array.from(uniqueConnections.values()))) {
    const model = modelByConnectionId.get(connection.id);
    if (!model) {
      throw new Error(
        `Missing semantic-model snapshot for connection ${connection.id}.`,
      );
    }

    const connectionSlug = connectionSlugs.get(connection.id)!;
    keepConnectionSnapshotDirs.add(connectionSlug);

    const connectionDir = path.join(connectionsDir, connectionSlug);
    const tableDir = path.join(connectionDir, "tables");
    await fs.mkdir(tableDir, { recursive: true });

    const existingTableSlugMap = await readSlugMap(tableDir);
    const sortedTables = sortByNameThenId(
      [...model.tables].map((table) => ({
        id: table.id,
        name: table.name,
        table,
      })),
    );
    const tableSlugs = resolveScopedSlugs({
      entities: sortedTables.map((item) => ({
        id: item.id,
        name: item.name,
      })),
      existingMap: existingTableSlugMap,
      preserveUnknown: false,
    });

    await writeYamlFile(path.join(connectionDir, "connection.yaml"), {
      id: connection.id,
      name: connection.name,
      status: connection.status,
      ownerAgentName: connection.ownerAgentName,
      hash: model.hash,
    });

    const keepTableFiles = new Set<string>([SLUG_MAP_FILE]);
    for (const item of sortedTables) {
      tableNameFromPayload(item.table);
      const fileName = `${tableSlugs.get(item.id)!}.yaml`;
      keepTableFiles.add(fileName);
      await writeYamlFile(path.join(tableDir, fileName), item.table);
    }
    await writeYamlFile(
      path.join(tableDir, SLUG_MAP_FILE),
      buildSlugMapRecord({
        slugs: tableSlugs,
        existingMap: existingTableSlugMap,
        preserveUnknown: false,
      }),
    );
    await removeStaleChildren(tableDir, keepTableFiles);
  }

  if (!preserveUnknownConnectionsGlobal) {
    const keep = new Set<string>([...keepConnectionSnapshotDirs, SLUG_MAP_FILE]);
    await removeStaleChildren(connectionsDir, keep);
  }
  await writeYamlFile(
    path.join(connectionsDir, SLUG_MAP_FILE),
    buildSlugMapRecord({
      slugs: connectionSlugs,
      existingMap: existingConnectionSlugMap,
      preserveUnknown: preserveUnknownConnectionsGlobal,
    }),
  );

  for (const entry of fetchedAgents) {
    const agentSlug = agentSlugs.get(entry.agent.id)!;
    const agentDir = path.join(agentsDir, agentSlug);
    const agentConnectionsDir = path.join(agentDir, "connections");
    await fs.mkdir(agentConnectionsDir, { recursive: true });

    await writeYamlFile(path.join(agentDir, "agent.yaml"), {
      id: entry.agent.id,
      name: entry.agent.name,
      orgId: params.org.id,
      orgName: params.org.name,
    });

    const sortedFields = [...entry.userContextResponse.userContext.fields].sort(
      (left, right) => left.key.localeCompare(right.key),
    );
    await writeYamlFile(path.join(agentDir, "user-context.yaml"), {
      hash: entry.userContextResponse.hash,
      status: entry.userContextResponse.userContext.status,
      fields: sortedFields,
    });

    await writeYamlFile(
      path.join(agentDir, "shareable-connections.yaml"),
      entry.shareable.map((connection) => ({
        id: connection.id,
        name: connection.name,
        databaseType: connection.databaseType,
        ownerAgent: connection.ownerAgent,
      })),
    );

    const keepConnectionRefs = new Set<string>();
    for (const { connection, model } of entry.models) {
      const connectionSlug = connectionSlugs.get(connection.id)!;
      keepConnectionRefs.add(connectionSlug);
      const connectionRefDir = path.join(agentConnectionsDir, connectionSlug);
      await fs.mkdir(connectionRefDir, { recursive: true });
      await writeYamlFile(path.join(connectionRefDir, "connection.yaml"), {
        id: connection.id,
        name: connection.name,
        status: connection.status,
        isShared: connection.isShared,
        ownerAgentName: connection.ownerAgentName,
        hash: model.hash,
        snapshotPath: `.inconvo/connections/${connectionSlug}`,
      });
      await removeStaleChildren(connectionRefDir, new Set(["connection.yaml"]));
    }

    if (!params.selectedConnectionId) {
      await removeStaleChildren(agentConnectionsDir, keepConnectionRefs);
    }
  }

  if (params.pruneUnselectedAgents !== false) {
    // Clean up stale agent directories only during explicit multi-agent pulls.
    const keepAgentDirs = new Set<string>([...agentSlugs.values(), SLUG_MAP_FILE]);
    await removeStaleChildren(agentsDir, keepAgentDirs);
  }

  await writeYamlFile(
    path.join(agentsDir, SLUG_MAP_FILE),
    buildSlugMapRecord({
      slugs: agentSlugs,
      existingMap: existingAgentSlugMap,
      preserveUnknown: preserveUnknownAgents,
    }),
  );

  return {
    pulledAgents: params.selectedAgents.length,
    pulledConnections: pulledConnectionCounts.reduce(
      (total, count) => total + count,
      0,
    ),
  };
}

export async function syncSingleAgentToWorkspace(params: {
  client: PlatformApiClient;
  repoRoot: string;
  agentId: string;
  selectedConnectionId?: string;
}): Promise<{
  pulledAgents: number;
  pulledConnections: number;
}> {
  const [org, agents] = await Promise.all([
    params.client.getOrg(),
    params.client.listOrgAgents(),
  ]);
  const agent = agents.find((item) => item.id === params.agentId);

  if (!agent) {
    throw new Error(`Agent ${params.agentId} not found in organization ${org.id}.`);
  }

  return pullAgentsToWorkspace({
    client: params.client,
    repoRoot: params.repoRoot,
    org,
    selectedAgents: [agent],
    selectedConnectionId: params.selectedConnectionId,
    pruneUnselectedAgents: false,
  });
}
